sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:15.04
  - ./test/download.sh
  - cp ./test/Dockerfile ./Dockerfile
  - docker build -t homecore .
  - docker run -d homecore bash > container_id

script:
  - docker exec `cat container_id` sh -c "echo hello-world"
