sudo: required

services:
  - docker

before_install:
  # - docker pull ubuntu:latest
  - docker pull carlad/sinatra
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - bundle exec rake test
  # - docker
  # - docker version
  # - docker run -d ubuntu:latest sh -c "while true; do sleep 5; done" > container_id
  # - docker logs `cat container_id`
  # - docker exec `cat container_id` sh -c "mkdir /repository"
  # - docker logs `cat container_id`
  # - docker exec `cat container_id` sh -c "cd /repository ; git clone https://github.com/tdeheurles/homecores"
  # - docker logs `cat container_id`
  # - docker exec `cat container_id` sh -c "cd /repository/homecores ; ./test/test.sh"
  # - docker logs `cat container_id`
