sudo: required

services:
  - docker

cache:
  directories:
    - test/downloads

before_install:
  - docker pull ubuntu:15.04
  - chmod +x ./test/download.sh
  - ./test/download.sh
  - cp ./test/Dockerfile ./Dockerfile
  - docker build -t homecore .
  - docker run -d homecore bash > container_id
  - cat container_id

script:
  - docker exec `cat container_id` sh -c "echo hello-world"
