sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - curl

before_install:
  - docker version
  - cp test/nginx.Dockerfile Dockerfile
  - cp test/nginx.conf       nginx.conf
  - cp test/index.html       index.html
  - docker build -t hctest .

script:
  - container_id=`docker run --name hctest -d -p 9999:8000 hctest`
  - docker ps -a
  - echo $container_id
  - sudo lxc-attach -n "$(docker inspect --format '{{.Id}}' hctest)" -- bash -c ls
  - sudo lxc-attach -n "$(docker inspect --format '{{.Id}}' hctest)" -- bash -c "mkdir /somedir"
  - curl http://0.0.0.0:9999
  - sudo lxc-attach -n "$(docker inspect --format '{{.Id}}' hctest)" -- bash -c "echo \"exec changed me\" > /www/index.html"
  - curl http://0.0.0.0:9999

