sudo: required

services:
  - docker

before_install:
  - docker pull tdeheurles/vbox-vagrant:latest

script:
  - docker ps -a
  - ls -la
  - docker run -d tdeheurles/vbox-vagrant:latest sh -c "while true; do ping 8.8.8.8; done" > container_id
  - docker ps -a
  - cat container_id
  - ls -la
  - docker exec `cat container_id` sh -c "mkdir /repository"
  - ls -la
  - docker ps -a
  - docker exec `cat container_id` sh -c "cd /repository ; git clone https://github.com/tdeheurles/homecores"
  - ls -la
  - docker ps -a
  - docker exec `cat container_id` sh -c "cd /repository/homecores ; ./test/test.sh"
  - ls -la
  - docker ps -a
