sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:15.04
  - docker build -t homecore test/Dockerfile
  - docker run -d homecore bash

script:
  - docker exec homecore sh -c "echo hello-world"
