sudo: required

services:
  - docker

cache:
  directories:
    - test/downloads

before_install:
  - docker pull ubuntu:15.04
  - chmod +x ./test/download.sh
  - ./test/download.sh
  - cp ./test/Dockerfile ./Dockerfile
  - docker build -t homecore .

script:
  - docker run -d homecore sh -c "echo hello-world"
