sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - docker-1.8.1

before_install:
  - docker version
  - curl -sSL https://get.docker.com/ | sh
  - docker version
  - cp test/nginx.Dockerfile Dockerfile
  - cp test/nginx.conf       nginx.conf
  - cp test/index.html       index.html
  - docker build -t hctest .

script:
  - container_id=`docker run -d -p 9999:8000 hctest`
  - docker ps -a
  - echo $container_id
  - docker exec ${container_id} ls
  - docker exec ${container_id} sh -c "mkdir /somedir"
  - curl http://0.0.0.0:9999
  - docker exec ${container_id} sh -c "echo \"exec changed me\" > /www/index.html"
  - curl http://0.0.0.0:9999
