sudo: required

services:
  - docker

cache:
  directories:
    - test/downloads

before_install:
  - docker pull ubuntu:15.04
  - chmod +x ./test/download.sh
  - ./test/download.sh
  - cp ./test/Dockerfile ./Dockerfile
  - docker build -t homecore .
  # Finally we test the prerequisite (error if doesn't work)
  - docker run -d homecore sh -c "while true; do ping 8.8.8.8; done" > container_id

script:
  - docker exec `cat container_id` sh -c "mkdir /repository"
  - docker exec `cat container_id` sh -c "cd /repository ; git clone https://github.com/tdeheurles/homecores"