sudo: required

services:
  - docker

before_install:
  - echo "FROM ubuntu:15.04" > Dockerfile
  - docker build -t dockertest .

script:
  - container_id=`docker run -d dockertest sh -c "while true; do sleep 5; done"`
  - docker exec $container_id sh -c "id -a"
  - docker exec -u root $container_id sh -c "mkdir /repository"
  # - docker exec `cat container_id` /bin/bash -c "mkdir /repository"
  # - docker exec `cat container_id` /bin/bash -c "cd /repository ; git clone https://github.com/tdeheurles/homecores"
  # - docker exec `cat container_id` /bin/bash -c "cd /repository/homecores ; ./test/test.sh"
