sudo: required

services:
  - docker

before_install:
  - docker pull busybox:latest

script:
  - docker run -d busybox:latest /bin/bash -c "while true; do sleep 5; done" > container_id
  - docker version
  - docker ps -a
  - cat container_id
  - docker exec $(cat container_id) ls
