sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:latest

script:
  - docker run -d ubuntu:latest sh -c "while true; do sleep 5; done" > container_id
  - docker logs `cat container_id`
  - docker exec `cat container_id` sh -c "mkdir /repository"
  - docker logs `cat container_id`
  - docker exec `cat container_id` sh -c "cd /repository ; git clone https://github.com/tdeheurles/homecores"
  - docker logs `cat container_id`
  - docker exec `cat container_id` sh -c "cd /repository/homecores ; ./test/test.sh"
  - docker logs `cat container_id`
