sudo: required

services:
  - docker

cache:
  directories:
    - test/downloads

before_install:
  - docker pull tdeheurles/vbox-vagrant
  - docker run -d tdeheurles/vbox-vagrant sh -c "while true; do ping 8.8.8.8; done" > container_id
  - docker exec `cat container_id` sh -c "echo world"

script:
  - docker exec `cat container_id` sh -c "mkdir /repository"
  - docker exec `cat container_id` sh -c "cd /repository ; git clone https://github.com/tdeheurles/homecores"
  - docker exec `cat container_id` sh -c "cd /repository/homecores ; ./test/test.sh"
