sudo: required

services:
  - docker

before_install:
  - docker pull tdeheurles/vbox-vagrant:latest

script:
  - docker run -d tdeheurles/vbox-vagrant:latest /bin/bash -c "while true; do sleep 5; done" > container_id
  - docker exec `cat container_id` /bin/bash -c "mkdir /repository"
  - docker exec `cat container_id` /bin/bash -c "cd /repository ; git clone https://github.com/tdeheurles/homecores"
  - docker exec `cat container_id` /bin/bash -c "cd /repository/homecores ; ./test/test.sh"
