apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: __KUBERNETES_SSL_PATH__/__CA_PEM__
users:
- name: kubelet
  user:
    client-certificate: __KUBERNETES_SSL_PATH__/__WORKER_PEM__
    client-key: __KUBERNETES_SSL_PATH__/__WORKER_KEY_PEM__
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
