apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager

spec:
  hostNetwork: true

  containers:
  - name: kube-controller-manager
    image: gcr.io/google_containers/hyperkube:v__K8S_VERSION__
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --service-account-private-key-file=__KUBERNETES_SSL_PATH__/__APISERVER_KEY_PEM_NAME__
    - --root-ca-file=__KUBERNETES_SSL_PATH__/__CA_PEM_NAME__
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: __KUBERNETES_SSL_PATH__
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true

  volumes:
  - hostPath:
      path: __KUBERNETES_SSL_PATH__
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
