apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy

spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:v__K8S_VERSION__
    command:
    - /hyperkube
    - proxy
    - --master=https://__MASTER_IP__
    - --kubeconfig=/etc/kubernetes/worker-kubeconfig.yml
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: "ssl-certs"
      - mountPath: /etc/kubernetes/worker-kubeconfig.yml
        name: "kubeconfig"
        readOnly: true
      - mountPath: __KUBERNETES_SSL_PATH__
        name: "etc-kube-ssl"
        readOnly: true
  volumes:
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "kubeconfig"
      hostPath:
        path: "/etc/kubernetes/worker-kubeconfig.yml"
    - name: "etc-kube-ssl"
      hostPath:
        path: "__KUBERNETES_SSL_PATH__"