#cloud-config

users:
  - name: core
    passwd: __PASSWORD__
    ssh_authorized_keys:
      - ssh-rsa __ID_RSA__
    groups:
      - sudo
      - docker

coreos:
  etcd2:
    name:                        '__HOSTNAME__'
    initial-cluster-state:       'existing'
    initial-cluster:             '__ETCD_LEAD_NAME__=__ETCD_LEAD_PEER__,__HOSTNAME__=http://__IP_PUBLIC__:2380'
    initial-advertise-peer-urls: 'http://__IP_PUBLIC__:2380'
    listen-peer-urls:            'http://__IP_PUBLIC__:2380'
    listen-client-urls:          'http://__IP_PUBLIC__:2379,http://127.0.0.1:2379'
    advertise-client-urls:       'http://__IP_PUBLIC__:2379'

# config for bootstrapping
# name:                        __HOSTNAME__
# initial-cluster-state:       'new'
# initial-cluster:             '__HOSTNAME__=http://__PUBLIC_IP__:2380'
# initial-advertise-peer-urls: http://__PUBLIC_IP__:2380
# listen-peer-urls:            http://__PUBLIC_IP__:2380
# listen-client-urls:          http://__PUBLIC_IP__:2379, http://127.0.0.1:2379

# actual cloud-config :
# name:                         __HOSTNAME__
# initial-cluster-state:        'existing'
# initial-cluster:              '__ETCD_LEAD_NAME__=__ETCD_LEAD_PEER__,__HOSTNAME__=http://__IP_PUBLIC__:2380'
# initial-advertise-peer-urls:  http://__IP_PUBLIC__:2380
# listen-peer-urls:             http://__IP_PUBLIC__:2380
# listen-client-urls:           http://__IP_PUBLIC__:2379,http://127.0.0.1:2379
# advertise-client-urls:        http://__IP_PUBLIC__:2379

  units:
    - name: fleet.service
      command: start

    - name: etcd2.service
      command: start

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes

        [Service]
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStart=/usr/bin/kubelet \
            --api-servers=http://127.0.0.1:8080 \
            --allow-privileged=true \
            --config=/etc/kubernetes/manifests \
            --v=2
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: download_kubernetes.target
      command: start
      content: |
        [Unit]
        Description=Download kubernetes manifests
        Documentation=https://coreos.com/blog/introducing-the-kubelet-in-coreos/

        [Service]
        ExecStart=/usr/bin/wget                                                  \
            https://raw.githubusercontent.com/coreos/pods/master/kubernetes.yaml \
            -O /etc/kubernetes/manifests

        [Install]
        WantedBy=multi-user.target

    - name: kubectl.target
      command: start
      content: |
        [Unit]
        Description=Download kubectl

        [Service]
        ExecStart=/usr/bin/wget                                                                      \
            https://storage.googleapis.com/kubernetes-release/release/v1.0.3/bin/linux/amd64/kubectl \
            -O /home/core/kubectl/                                                                   \
            && chmod +x /home/core/kubectl                                                           \
            && cp /home/core/kubectl/kubectl /usr/bin/

        [Install]
        WantedBy=multi-user.target

hostname: __HOSTNAME__
