#cloud-config

users:
  - name: core
    passwd: __PASSWORD__
    ssh_authorized_keys:
      - ssh-rsa __ID_RSA__
    groups:
      - sudo
      - docker

coreos:
  units:
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes

        [Service]
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStart=/usr/bin/kubelet \
            --api-servers=http://127.0.0.1:8080 \
            --allow-privileged=true \
            --config=/etc/kubernetes/manifests \
            --v=2
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: kubectl.target
      command: start
      content: |
        [Unit]
        Description=Download kubectl

        [Service]
        ExecStartPre=/usr/bin/mkdir -p /home/core/programs/
        ExecStart=/usr/bin/wget                                                                      \
            https://storage.googleapis.com/kubernetes-release/release/v1.0.3/bin/linux/amd64/kubectl \
            -O /home/core/kubectl/                                                                   \
            && chmod +x /home/core/kubectl                                                           \
            && cp /home/core/programs/kubectl /usr/bin/

        [Install]
        WantedBy=multi-user.target

hostname: __HOSTNAME__
