#cloud-config

hostname: __HOSTNAME__

users:
  - name: __USERNAME__
    ssh_authorized_keys:
      - ssh-rsa __ID_RSA__
    groups:
      - sudo
      - docker

coreos:
  units:
__WRITE_PUBLIC_IP__
__ETCD2__
__FLANNEL__
__KUBECTL__
__KUBELET__

write_files:
__FILE_WRITE_IP__
__FILE_WRITE_FLANNEL_PUBLIC_IP__
__FILE_SED_KUBERNETES_PUBLIC_IP__
