#cloud-config

users:
  - name: core
    passwd: __PASSWORD__
    ssh_authorized_keys:
      - ssh-rsa __ID_RSA__
    groups:
      - sudo
      - docker

coreos:
  etcd2:

    # default: 'default'
    # human-readable name for this member.
    name: __HOSTNAME__

    # discovery URL used to bootstrap the cluster
    discovery: https://discovery.etcd.io/__DISCOVERY_TOKEN__

    # default : 'http://localhost:2379,http://localhost:4001'
    # list of this member's client URLs to advertise to the public.
    # The client URLs advertised should be accessible to machines that talk 
    # to etcd cluster. etcd client libraries parse these URLs to connect to the 
    # cluster.
    advertise-client-urls: http://__IP_PUBLIC__:2379,http://__IP_PUBLIC__:4001

    # 'http://localhost:2380,http://localhost:7001'
    # list of this member's peer URLs to advertise to the rest of the cluster.
    initial-advertise-peer-urls: http://__IP_PUBLIC__:2380

    # 'http://localhost:2379,http://localhost:4001'
    # list of URLs to listen on for client traffic.
    listen-client-urls: http://__IP_PUBLIC__:2379,http://__IP_PUBLIC__:4001

    # 'http://localhost:2380,http://localhost:7001'
    # list of URLs to listen on for peer traffic.
    listen-peer-urls: http://__IP_PUBLIC__:2380

  units:
    - name: fleet.service
      command: start

    - name: etcd2.service
      command: start

    - name: hyberkube.target
      command: start
      content: |
        [Unit]
        Description=Download Hyperkube
        Requires=etcd2.service fleet.service docker.service
        After=etcd2.service fleet.service docker.service

        [Service]
        ExecStart=/usr/bin/docker pull __IMAGE_KUBERNETES__

    - name: kubernetes.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes master services
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=hyberkube.target
        After=hyperkube.target

        [Service]
        ExecStart=/usr/bin/docker run --net=host -v /var/run/docker.sock:/var/run/docker.sock __IMAGE_KUBERNETES__ /hyperkube kubelet --api_servers=http://localhost:8080 --v=2 --address=0.0.0.0 --enable_server --hostname_override=127.0.0.1 --config=/etc/kubernetes/manifests

#    - name: kube-proxy.service
#      command: start
#      content: |
#        [Unit]
#        Description=Kubernetes proxy service
#        Requires=hyperkube.target
#        After=hyperkube.target
#
#        [Service]
#        ExecStart=/usr/bin/docker run --privileged --net=host __IMAGE_KUBERNETES__ /hyperkube proxy --master=http://localhost:8080 --v=2

    - name: galliasphere.service
      command: start
      content: |
        [Unit]
        Description=site galliasphere.com
        Requires=docker.service
        After=docker.service

        [Service]
        ExecStart=/usr/bin/docker run -p 80:80 nginxtest:latest

hostname: __HOSTNAME__
